### ISSUE TITLE
Get peer list API call problem

### ISSUE THREAD

**Issue by andreafspeziale** [dakk/liskapi#22]
It should accept as filter call the state of peer as string.
(https://lisk.io/documentation?i=lisk-docs/APIReference#get-peers-list)
```
lisk.getPeersList ()
    .paginate ({ state: "2", limit: 3 })
    .call ()
    .then ((res) => {
        console.log (`Get peers of Liskword\n ${JSON.stringify (res)}`);
    })
    .catch ((err) => {
        console.log ('Got an error in getting peers\n', err);
    });
```

Is not getting the ones with state = 2

**Comment by andreafspeziale** [comment]
The API endpoint is working fine, I've also updated the official lisk-docu because there was an error.
The state API filter is accepting an Integer not a String.

**Comment by dakk** [comment]
The state parameter is not a paginate parameter but a query parameter. Paginate should get only offset and limit.
In addition, state should be an integer as you told.

```javascript
lisk.getPeersList ({state: 2})
    .paginate ({ limit: 3 })
    .call ()
    .then ((res) => {
        console.log (`Get peers of Liskword\n ${JSON.stringify (res)}`);
    })
    .catch ((err) => {
        console.log ('Got an error in getting peers\n', err);
    });
```

**Comment by andreafspeziale** [comment]
Ok, the error seems to be in the api.js declaration.
I'm gonna fix it right now.
